// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5yjl7sX7MF6WmzLaVE3Ls_Su3YO9DpUk',
    appId: '1:292510166407:web:d7c812cfd86bf64aa57722',
    messagingSenderId: '292510166407',
    projectId: 'hostelmanagement-113cf',
    authDomain: 'hostelmanagement-113cf.firebaseapp.com',
    storageBucket: 'hostelmanagement-113cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzfrNJsCVc3iR3xAh_ajPHDw2vAck91HI',
    appId: '1:292510166407:android:12df005904739aa1a57722',
    messagingSenderId: '292510166407',
    projectId: 'hostelmanagement-113cf',
    storageBucket: 'hostelmanagement-113cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUZoYhvmnYlWrZwPILKfF_j4C4aLfqk4',
    appId: '1:292510166407:ios:43dc0b894c850ca0a57722',
    messagingSenderId: '292510166407',
    projectId: 'hostelmanagement-113cf',
    storageBucket: 'hostelmanagement-113cf.appspot.com',
    iosBundleId: 'com.example.hostelmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUZoYhvmnYlWrZwPILKfF_j4C4aLfqk4',
    appId: '1:292510166407:ios:8b5ff50489106b70a57722',
    messagingSenderId: '292510166407',
    projectId: 'hostelmanagement-113cf',
    storageBucket: 'hostelmanagement-113cf.appspot.com',
    iosBundleId: 'com.example.hostelmanagement.RunnerTests',
  );
}
